# Generated by Django 4.2 on 2023-04-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airqualityreading',
            name='co2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
